SQF/dayz_code/actions/player_eat.sqf

After eating in a vehicle that should drop an empty can, client RPT would show:
Error Undefined variable in expression: _itemtodrop

undefined variable _itemtodrop     fixes #1535

---

SQF/dayz_code/compile/fn_gearMenuChecks.sqf

Added it's class to the vehicles that except themselves from the locks

Should fix #1555

---

SQF/dayz_epoch_b/stringtable.xml

for commits done half year ago

Another batch of czech

---

SQF/dayz_code/Configs/CfgLoot/CfgLoot.hpp
SQF/redryder/$PBOPREFIX$
SQF/redryder/config.cpp

The Red Ryder should work properly for the next update

Fixed a sound error and organized file more

---

SQF/dayz_code/compile/wild_spawnZombies.sqf

this should fix some issues with zombies not having loot while using custom loot tables ;)

custom CfgVehicles? i dont think so

---

SQF/dayz_code/Configs/CfgLoot/CfgLoot.hpp

Available as "farmweapons" and "shotgunsingleshot". Chance of spawn is 0.06.
Classname: "RedRyder"

Added RedRyder BB Gun to Loot Table

---

CHANGE LOG 1.0.5.2.txt

[FIXED] Trader menu expected array error #1618-1620 @ebaydayz

[FIXED] Trader menu expected array error

---

SQF/dayz_code/init/compiles.sqf

which made users able to walk around but not see anything but DayZ Image

Fixed Black Screen on Loading

---

CHANGE LOG 1.0.5.2.txt

Edited change-log to add loading fix

---

SQF/dayz_code/Configs/CfgMagazines/Planting.hpp

The type attribute was defined twice for ItemHempPlant

Fix for compile error "Item listed twice..."

---

SQF/dayz_code/compile/player_switchModel.sqf

When changing skins you'd have to select whether or not you want to display your name again, this fixed that. Unless it was intentional ofc.

Persistent Name Tag Setting

---

SQF/dayz_code/medical/publicEH/medTransfuse.sqf

Gives more blood, false positive on anti-hack and bad practice.

Fix blood over maximum

---

SQF/dayz_epoch_b/stringtable.xml

See https://github.com/vbawol/DayZ-Epoch/pull/1567
This was done with Google Translate so apologies if the translations are botched.

Add strings for sledgehammer crafting fix

---

SQF/dayz_code/Configs/CfgMagazines.hpp
SQF/dayz_code/Configs/CfgVehicles/DZE/VaultStorage.hpp
SQF/dayz_epoch_b/stringtable.xml

I'm not really sure if this will work but it should I think.

Russian localization update, safe localization

---

SQF/dayz_code/Configs/CfgMagazines/DZE/Items.hpp
SQF/dayz_code/Configs/CfgMagazines/DZE/Misc.hpp
SQF/dayz_code/compile/fn_selfActions.sqf
SQF/dayz_code/stringtable.xml

I've made some changes to fn_selfActions.sqf and I'm not sure about them since I'm not familiar with Arma coding. I think it should work but @ebaydayz please double check it and fix it if needed. I'm also planning to make a PR (move some hardcoded stuff into stringtable) to vanilla DayZ and I hope you can review it @ebaydayz.

More progress on localization support

---

SQF/dayz_code/Configs/CfgMagazines/Clothing/EpochSkins.hpp
SQF/dayz_code/Configs/CfgMagazines/DZE/Currency/AluminumBar.hpp
SQF/dayz_code/Configs/CfgMagazines/DZE/Currency/BronzeBar.hpp
SQF/dayz_code/Configs/CfgMagazines/DZE/Currency/CopperBar.hpp
SQF/dayz_code/Configs/CfgMagazines/DZE/Currency/GoldBar.hpp
SQF/dayz_code/Configs/CfgMagazines/DZE/Currency/SilverBar.hpp
SQF/dayz_code/Configs/CfgMagazines/DZE/Currency/TinBar.hpp
SQF/dayz_code/Configs/CfgMagazines/DZE/Items.hpp
SQF/dayz_code/Configs/CfgMagazines/DZE/ModularBuilding.hpp
SQF/dayz_code/actions/player_heliLift.sqf
SQF/dayz_code/compile/fn_selfActions.sqf
SQF/dayz_code/stringtable.xml

I won't be able to fix any typos today. So, review it and I'll fix them tomorrow.

more localization work

---

SQF/dayz_code/Configs/CfgMagazines/DZE/ModularBuilding.hpp

The full_cinder_wall_kit had the same weight as the half. I just increased the weight by almost the double amout.

Increased weight of full_cinder_wall_kit

---

SQF/dayz_code/Configs/CfgLoot/Buildings/Military.hpp

It does not feel right, when you enter a military area and see only Worker Zombies. I changed the Zombie Typs of the buildings to look more like a military area.

Changed more Zombies Typs

---

SQF/dayz_code/Configs/CfgServerTrader/Category/FriendlyBackpacks.hpp

Backpack prices were wrong. It does not make sense to buy a smaller backpack for a higher price than a bigger backpack.

Backpack prices changed

---

SQF/dayz_code/actions/modular_build.sqf
SQF/dayz_code/actions/player_build.sqf
SQF/dayz_code/actions/player_upgrade.sqf
SQF/dayz_code/stringtable.xml

This changes a few functions that were being used to use the already
defined variables instead
Fixed a few string issues with Advanced trading and plot managment.

Tidyness changes

---

SQF/dayz_sfx/CfgSounds.hpp

Fix backpack sound error, re: @ndavalos https://github.com/EpochModTeam/DayZ-Epoch/issues/1712#issuecomment-236391838

Backpack sound fix

---

SQF/dayz_code/Configs/CfgLoot/Groups/Buildings/Industrial.hpp
SQF/dayz_code/Configs/CfgLoot/Groups/Buildings/Military.hpp

Changed the big duct tape and binocular spawn.

Small loot tweaks for balance

---

SQF/dayz_code/Configs/CfgLoot/Buildings/Military.hpp
SQF/dayz_code/Configs/CfgLoot/Groups/Buildings/Hangar.hpp
SQF/dayz_code/Configs/CfgLoot/Groups/Buildings/Industrial.hpp
SQF/dayz_code/Configs/CfgLoot/Groups/Buildings/Military.hpp
SQF/dayz_code/Configs/CfgLoot/Groups/Generic.hpp
SQF/dayz_code/Configs/CfgLoot/Groups/Zombies/Police.hpp

Updating loot tables and loot chances, should be good now. Let me now if you think something is wrong here.

Updating loot table and loot chances

---

SQF/dayz_code/external/R3F_Realism/R3F_Weight/Weapons/Tools.hpp

Adding missing items when using dayz_knifeDulling = true; and dayz_matchboxCount = true; and ItemFishingPole

Adding missing items

---

SQF/dayz_code/Configs/CfgWeapons/Rifles/G36.hpp
SQF/dayz_code/Configs/CfgWeapons/Rifles/G36C.hpp
SQF/dayz_code/Configs/CfgWeapons/Rifles/L85.hpp
SQF/dayz_code/Configs/CfgWeapons/Rifles/M16A2.hpp
SQF/dayz_code/Configs/CfgWeapons/Rifles/M16A4.hpp
SQF/dayz_code/Configs/CfgWeapons/Rifles/M4A1.hpp
SQF/dayz_code/compile/player_harvest.sqf

Updating the CfgWeapons based on that topic: 
https://github.com/EpochModTeam/DayZ-Epoch/issues/1738
Ive updated only the Stang, G36, L85 and M8 weapons. All other weapons should be good. AKM and SA85 mags can be easily converted.
Increased the number for harvesting wood to make it similar like epoch 1051.

Updating CfgWeapons and harvest Wood

---

SQF/dayz_code/Configs/CfgServerTrader/Category/FriendlyBuildingSupplies.hpp
SQF/dayz_code/Configs/CfgServerTrader/Category/FriendlyToolbeltItems.hpp
SQF/dayz_code/Configs/CfgServerTrader/Category/FriendlyVehicleParts.hpp

Moving mixed oil to building supplies and removing GPS, Range Finder and Night Vision from buylist. These items should be rare items and harder to find than other items.

Small trader changes

---

SQF/dayz_code/Configs/CfgMagazines/Magazines/762x51.hpp
SQF/dayz_code/Configs/CfgMagazines/Magazines/Misc.hpp
SQF/dayz_code/stringtable.xml

Adding 
Mk17
Mk17 SD
M107
KSVK
L115
VSS

Add missing re-combine actions for magazines

---

SQF/dayz_code/Configs/CfgLoot/Groups/Ammo.hpp
SQF/dayz_code/Configs/CfgLoot/Groups/AmmoBox.hpp
SQF/dayz_code/Configs/CfgLoot/Groups/Weapons.hpp
SQF/dayz_code/Configs/CfgMagazines/Magazines/Shotgun.hpp
SQF/dayz_code/Configs/CfgServerTrader/Category/BanditAmmunition.hpp
SQF/dayz_code/Configs/CfgServerTrader/Category/BanditWeapons.hpp
SQF/dayz_code/Configs/CfgServerTrader/Category/FriendlyAssaultRifle.hpp
SQF/dayz_code/Configs/CfgServerTrader/Category/FriendlyLightMachineGun.hpp
SQF/dayz_code/Configs/CfgServerTrader/Category/NeutralBlackMarketAmmo.hpp
SQF/dayz_code/Configs/CfgServerTrader/Category/NeutralBlackMarketWeapons.hpp
SQF/dayz_code/Configs/CfgServerTrader/Category/NeutralHelicopterUnarmed.hpp
SQF/dayz_code/external/R3F_Realism/R3F_Weight/Magazines/ShotgunAmmo.hpp
SQF/dayz_code/external/R3F_Realism/R3F_Weight/Weapons/LMG.hpp
SQF/dayz_code/external/R3F_Realism/R3F_Weight/Weapons/Rifles.hpp
SQF/dayz_code/stringtable.xml

Adding these weapons to epoch with ammo:
Mk16 Aimpoint SD
Mk16 CQC
Mk16 CQC EOTech
Mk16 EGLM EOTech,(40mm)
Mk16 EGLM RCO,(40mm)
Mk16 EOTech
Mk16 Mk4CQ/T
Mk16 EGLM EOTech
Mk17 Sniper
Mk17 Aimpoint
Mk17 Aimpoint SD
Mk17 EGLM ACOG,(40mm)
L85A2 ACOG
L86A2 ACOG LMG
AA12 Military Shotgun
M110_NVG_EP1

Adding many new weapons

---

SQF/dayz_code/Configs/RscDisplay/doorManagement/doorAccess.hpp
SQF/dayz_code/Configs/RscDisplay/doorManagement/doorManagement.hpp
SQF/dayz_code/Configs/RscDisplay/plotManagement.hpp
SQF/dayz_code/actions/doorManagement/doorAddFriend.sqf
SQF/dayz_code/actions/doorManagement/doorNearbyHumans.sqf
SQF/dayz_code/actions/plotManagement/plotAddFriend.sqf
SQF/dayz_code/actions/plotManagement/plotNearbyHumans.sqf

This correctly sorts the nearby humans list in both mods, I have this
running on my 1051 server with no issues, @ebaydayz please advise if
this is not right, I've tested it pretty well and it is indeed selecting
the right person/UID

Plot / door management userlist sorting

---

SQF/dayz_code/actions/AdvancedTrading/functions/z_at_displayVehicleInfo.sqf

This fixes the issue that @ndavalos found:
https://github.com/EpochModTeam/DayZ-Epoch/issues/1712#issuecomment-241289082

Advanced trading fix

---

CHANGE LOG 1.0.6.txt
SQF/dayz_code/configVariables.sqf

Change log update and switch boolean from false to true.

Salvage vehicles last changes

---

SQF/dayz_code/Configs/CfgMagazines/Items/Sandbag.hpp
SQF/dayz_code/Configs/CfgMagazines/Planting.hpp
SQF/dayz_code/Configs/CfgWeapons/Tools/Chainsaw.hpp
SQF/dayz_code/Configs/CfgWeapons/Weapon/Sniper/M107.hpp
SQF/dayz_code/stringtable.xml

Adds some more text to localization, Moves sandbags around so they are
all next to each other.

Localization additions

---

SQF/dayz_code/medical/transfusion.sqf
SQF/dayz_server/compile/server_handleSafeGear.sqf

Simplifies the serverside logging to be more human readable
Removes duplicate transfusion text

Minor fixes

---

SQF/dayz_code/Configs/RscDisplay/advancedTrading.hpp
SQF/dayz_code/actions/AdvancedTrading/functions/z_at_payDefault.sqf
SQF/dayz_code/actions/AdvancedTrading/functions/z_at_returnChange.sqf
SQF/dayz_code/actions/AdvancedTrading/functions/z_at_sellItems.sqf
SQF/dayz_code/stringtable.xml

Fixes combining/returnChange to squash gems into usable currency so they
can properly be used in the economy
Stringtable fixes for duplicates

Advance trading gem fixes/localizations

---

SQF/dayz_code/Configs/CfgVehicles/Helicopter/MI17.hpp
SQF/dayz_code/Configs/CfgVehicles/Helicopter/UH1H.hpp
SQF/dayz_code/stringtable.xml

Ive added a lot german string and corrected a few. This should be good for DayZ Mod too. 
We are missing a few DZE variants of our vehicles. Ive added the UH-1H DZE and changed a few displaynames. I accidentally took the classnames as displaynames.

Addong german strings, updating heli displaynames, new UH-1H DZE

---

SQF/dayz_code/Configs/CfgMagazines/Attachments/GP25.hpp

GP25 had the wrong description text.

Fixed GP25 wrong text

---

SQF/dayz_code/compile/fn_gearMenuChecks.sqf
SQF/dayz_code/init/variables.sqf

This makes it so M240Nest can be maintained. (Which it should be)

Add M240Nest_DZ to maintain classes variable.

---

SQF/dayz_code/Configs/CfgMagazines/DZE/Items.hpp
SQF/dayz_code/Configs/CfgMagazines/DZE/Misc.hpp
SQF/dayz_code/Configs/CfgServerTrader/Category/FriendlyBuildingSupplies.hpp
SQF/dayz_code/Configs/CfgVehicles/DZE/Prop_Defs.hpp
SQF/dayz_code/compile/dze_buildChecks.sqf
SQF/dayz_code/external/R3F_Realism/R3F_Weight/Magazines/BuildingSupplies.hpp
SQF/dayz_code/stringtable.xml
Server Files/SQL/1.0.6_Updates.sql

Plot pole:
Sanity change since the plot pole is not fixed at 30 meters and is configurable.
dze_BuildChecks:
This changes the reasons to be more understandable about why you can't build somewhere.
i.e: You don't have plot access. 
Previously it just lumped everything into "you need a plot pole to do this"
Some localization fixes to be more englishy.

Rename plot pole and dze_BuildChecks changes.

---

SQF/dayz_code/Configs/CfgExtra/snappoints.hpp
SQF/dayz_code/actions/AdvancedTrading/functions/z_at_buyItems.sqf
SQF/dayz_code/actions/AdvancedTrading/functions/z_at_canAfford.sqf
SQF/dayz_code/actions/AdvancedTrading/functions/z_at_fillBuyableList.sqf
SQF/dayz_server/compile/server_handleSafeGear.sqf

Revisions for #1777

---

SQF/dayz_code/Configs/CfgMagazines/Items/Sandbag.hpp
SQF/dayz_code/Configs/CfgVehicles/DZE/Doors.hpp
SQF/dayz_code/Configs/CfgVehicles/DZE/LockboxStorage.hpp
SQF/dayz_code/Configs/CfgVehicles/DZE/ModularBuilding.hpp
SQF/dayz_code/Configs/CfgVehicles/DZE/Prop_Defs.hpp
SQF/dayz_code/Configs/CfgWeapons/Tools/Knife.hpp
SQF/dayz_code/Configs/CfgWeapons/Tools/Toolbox.hpp
SQF/dayz_code/stringtable.xml

- adding many new german strings
- corrected and changed a few because many were too long
- changed the safe description because it was a way too long even 1051 half of the description was not visible. It is a better now.
- adding new localizations for some building items. Ive changed the name of some buldings like Small Wall to Wood Wall to get a better consistency with the buildable items. Even the same in german. 
- remove options are now listet in the stringtable
- almost every english string should have an german string too now
- adding the Skin_Sniper1W_DZN string for better compatibility with namalsk @ndavalos

Adding many new strings

---

SQF/dayz_code/compile/vehicle_getOut.sqf
SQF/dayz_code/system/scheduler/sched_gravity.sqf

Reduce client RPT spam

---

SQF/dayz_code/Configs/CfgVehicles/DZE/Prop_Defs.hpp
SQF/dayz_code/init/variables.sqf

CanvasHut_DZ had no remove option.

Adding CanvasHut_DZ to DZE_isRemovable

---

SQF/dayz_code/compile/dze_buildChecks.sqf

Fixes the proper distance checks for dze_buildChecks.
Thanks to @SmokeyBR https://github.com/EpochModTeam/DayZ-Epoch/issues/1766#issuecomment-263010635

dze_buildchecks plot pole distance fix

---

SQF/dayz_code/actions/modular_build.sqf
SQF/dayz_code/actions/player_build.sqf
SQF/dayz_server/compile/server_publishFullObject.sqf
SQF/dayz_server/compile/server_publishVehicle.sqf
SQF/dayz_server/compile/server_publishVehicle2.sqf
SQF/dayz_server/compile/server_publishVehicle3.sqf
SQF/dayz_server/compile/server_updateObject.sqf

Tidys up server RPT
Also make the combination rolling text overwrite the previous build
spam.

Move more debug lines to #ifdef

---

SQF/dayz_code/Configs/CfgWeapons/CfgWeapons.hpp
SQF/dayz_code/Configs/CfgWeapons/Item/Documents.hpp
SQF/dayz_code/Configs/CfgWeapons/Weapon/Sniper/VSSVintorez.hpp
SQF/dayz_code/stringtable.xml

I think the new items are a good addition for server admins. Most items were used by certain scripts, so a few new items are a good option to expand the possibilities. Admins should decide what items they want to use and can add that to the loot table then.
The new items are based of the Kostey items and are toolitems.
Ive added a new DZE version of the VSS Vintorez as well because in 1.0.5.1 the Vintorez spawns with a 20 rounds magazine.

Adding 13 new items and a DZE version of the vss vintorez

---

Server Files/MPMissions/DayZ_Epoch_16.Panthera2/mission.sqm
Server Files/MPMissions/DayZ_Epoch_23.cmr_ovaron/mission.sqm

Fixing very old spelling mistake

---

SQF/dayz_server/compile/server_updateObject.sqf

This reverts
https://github.com/EpochModTeam/DayZ-Epoch/commit/ce75f87e1da90c5eb13fcd214b4ebef0a8bd566f

Revert force coins update, Add seperate coins update

---

SQF/dayz_server/compile/server_updateObject.sqf

server_updateObject better version.

---

SQF/dayz_code/stringtable.xml

Adding and reworking some russian translation.

Russian translations in stringtable.xml

---

SQF/dayz_code/stringtable.xml

Adding and reworking some russian translation. Again.

stringtable.xml

---

SQF/dayz_code/Configs/CfgVehicles/DZE/Prop_Defs.hpp

Fixes: https://github.com/EpochModTeam/DayZ-Epoch/issues/1945

Fix BagFenceRound making the player slide

---

SQF/dayz_code/compile/fn_selfActions.sqf

This will be easier for custom mods that use the lock checking
(vkc/virtual garage etc) as well as removing overhead from
fn_selfActions

Condense locked status to a variable

---

SQF/dayz_server/compile/server_publishVehicle.sqf
SQF/dayz_server/compile/server_publishVehicle2.sqf
SQF/dayz_server/compile/server_publishVehicle3.sqf
SQF/dayz_server/compile/server_swapObject.sqf

Seems like these were forgotten at some point, the rest are diag_tickTime

Switch forgotten "time" to "diag_tickTime"

---

SQF/dayz_code/actions/ammo.sqf

https://github.com/DayZMod/DayZ/commit/e7ffb88075b2e71ef442946af0663ade57ea01c4

Add extra magazine instead of reloading current one

---

SQF/dayz_server/system/server_monitor.sqf
SQF/dayz_server/system/server_vehicleSync.fsm

This will suppress ```11:57:37 "INFO: needUpdate_objects=[edeb6080# 1058980: hmmwv.p3d]"``` if ```//#define OBJECT_DEBUG``` is commented out

Move more diag_log to debug lines

---

SQF/dayz_code/actions/modular_build.sqf
SQF/dayz_code/actions/player_build.sqf
SQF/dayz_code/actions/player_upgrade.sqf

Safe/lockbox will be able to be auto unlocked after placing due to setting dayz_combination to _combination.
Locked doors use DZE_Lock_Door instead.

Fix auto unlock to function like storage

---

SQF/dayz_code/stringtable.xml

This changes many german strings and is related to this old request by @DAmNRelentless 
https://github.com/EpochModTeam/DayZ-Epoch/pull/1917
I spoke with DAmNRelentless and he is ok with adding this stringtable update. This contains most of the changes in the commit from above. 
I changed the Vault string again because it is still a way to long to fit in left text box. Perhaps @dreamforceinc you can change the russian string that it has the same length like the english one.
Fell free to post changes under this request. For all additional changes please post always the complete <Key ID="">

German stringstable overhaul again

---

SQF/dayz_code/Configs/CfgVehicles/DZE/Doors.hpp
SQF/dayz_code/stringtable.xml

This adds a localization for all doors as objects. 
@dreamforceinc can you give me the correct russain localization for the 4 new strings in this commit?

Adding door localization

---

SQF/dayz_code/Configs/CfgMagazines/Crafting/equip_carbomb.hpp
SQF/dayz_code/Configs/CfgMagazines/DZE/Misc.hpp
SQF/dayz_code/stringtable.xml

7 new items - server admins can add them if desired
Adding a better and some missing localizations
Adding a localization for the car bomb

7 new items, missing localizations

---

SQF/dayz_code/Configs/CfgVehicles/Car/Pickup_PK_INS.hpp

fix Pickup_PK_GUE_DZE1 upgrade

fix Pickup_PK_GUE_DZE1 upgrade

---

SQF/dayz_code/Configs/CfgVehicles/Car/ArmoredSUV.hpp

fix ArmoredSUV_PMC_DZE2 upgrade

fix ArmoredSUV_PMC_DZE2 upgrade

---

SQF/dayz_code/Configs/CfgVehicles/Car/Offroad_DSHKM_INS.hpp

fix Offroad_DSHKM_Gue_DZE1 upgrade

fix Offroad_DSHKM_Gue_DZE1 upgrade

---

CHANGE LOG 1.0.6.3.txt
SQF/dayz_code/Configs/CfgVehicles/Zeds/SwarmZeds.hpp
SQF/dayz_code/Configs/CfgVehicles/Zeds/Zeds.hpp
SQF/dayz_code/actions/player_flipvehicle.sqf

Zombies can wear a lootable backpack now. Server admins have to add a function for adding backpacks. It is not included at the moment

 Adding backpack support for zombies 

---

SQF/dayz_code/init/variables.sqf
SQF/dayz_code/system/player_monitor.fsm
SQF/dayz_code/system/player_spawn_2.sqf

The client filters for this data every 10 seconds and does nothing with it.

Removing unused variable dayz_currentGlobalAnimals

---

CHANGE LOG 1.0.7.txt

I know I haven't been here for a while but this typo annoys me. 😁

Fixed typo

---

SQF/dayz_server/system/scheduler/sched_init.sqf
SQF/dayz_server/system/scheduler/sched_traps.sqf
SQF/dayz_server/system/server_monitor.sqf

This is a simple check and it doesn't need to run on its own thread.

Move bear trap monitor to the server scheduler.

---

SQF/dayz_code/Configs/rscTitles.hpp
SQF/dayz_code/compile/keyboard.sqf
SQF/dayz_code/compile/player_updateGui.sqf
SQF/dayz_code/compile/ui_changeDisplay.sqf
SQF/dayz_code/configVariables.sqf
SQF/dayz_code/init/compiles.sqf
SQF/dayz_code/init/variables.sqf
SQF/dayz_code/medical/publicEH/medBandaged.sqf
SQF/dayz_code/medical/publicEH/medMorphine.sqf
SQF/dayz_code/stringtable.xml
SQF/dayz_code/system/scheduler/sched_gui.sqf

This update allows players to select among 5 different styles of status icons by pressing the F3 key or by setting in the game options menu. The setting saves to the player profile so it is persistent after server restart.

Player Adjustable Status UI Icons

---

SQF/dayz_code/Configs/CfgVehicles/Car/UAZ_AGS.hpp
SQF/dayz_code/Configs/CfgVehicles/Car/UAZ_SPG.hpp
SQF/dayz_code/Configs/CfgVehicles/CfgVehicles.hpp
SQF/dayz_code/stringtable.xml

UAZ with AGS and SPG

---

SQF/dayz_code/Configs/CfgVehicles/Car/UAZ_SPG.hpp
SQF/dayz_code/stringtable.xml

UAZ (SPG-9) for CDF and TK

---

SQF/dayz_code/compile/fn_inAngleSector.sqf

Update fn_inAngleSector.sqf - private fix

---

SQF/dayz_code/compile/player_attackfsmdelay.sqf

Update player_attackfsmdelay.sqf - private fix

---

SQF/dayz_code/compile/fn_buildWeightedArray.sqf

private fix fn_buildWeightedArray.sqf

---

SQF/dayz_code/compile/fn_inString.sqf

private fix fn_inString.sqf

---

SQF/dayz_code/compile/player_projectileNear.sqf

private fix player_projectileNear.sqf

---

SQF/dayz_code/compile/fn_selectRandomLocation.sqf

private fix fn_selectRandomLocation.sqf

---

SQF/dayz_code/compile/fnc_getSetPos.sqf

private fix fnc_getSetPos.sqf
