EpochModTeam/DayZ-Epoch

SQF/dayz_code/compile/player_switchModel.sqf

The deleteGroup command requires the group to be local to the machine executing it:
https://community.bistudio.com/wiki/deleteGroup
When a player changes clothes a new group is created. The player is switched into a new unit in the new group, and then his old group is left empty. Because the old group is local to the player, it will not be deleted by server_cleanupGroups until he disconnects and it is transferred to the server. 
We should delete the old group immediately rather than wait for the player to disconnect. This will prevent the excessive accumulation of empty groups when players change clothes a lot. It will help with the seagull spawn issue which happens when there are more than 144 groups on side WEST:
https://community.bistudio.com/wiki/createGroup
I have been running this …

Delete old group after changing clothes

---

SQF/dayz_code/compile/zombie_generate.sqf

Fixes a zombie loot error when using loot tables in mission file.

DZE_MissionLootTable fix

---

Server Files/SQL/add_recommended_mysql_events.sql

LandRover vehicles are being ignored with this script.  If you escape the '_' (underscore) with '\' it will only look for the '_' (underscore) character used with all build able land objects.  Currently LandRover vehicles will not be unlocked or deleted, as they are ignored with the current 'Land%' match.

Add the _ to the Land and escape the character

---

SQF/dayz_code/Configs/CfgLoot/CfgLoot.hpp

Forgot to add the ammo.
Added ammo to "hunter", "generic" and "office". Chance of spawn is 0.05
Classname: "350Rnd_BB_Magazine"

Added RedRyder BB Gun Ammo to Loot Table

---

SQF/dayz_code/compile/player_traderMenuConfig.sqf

TraderItemList and TraderCatList should be initialized as arrays, not numbers. Fixes this error:
```
Error in expression < 0;
if (_index < 0) exitWith {};
while {count TraderItemList < 1} do { sleep 1; >
Error position: <count TraderItemList < 1} do { sleep 1; >
Error count: Type Number, expected Array,Config entry
File z\addons\dayz_code\compile\player_traderMenuHive.sqf, line 174
```
See: https://github.com/vbawol/DayZ-Epoch/issues/1616
Tested buying and selling to all Stary and Bash traders as well as the boat dealer with these changes. No more error or problems.

Fix trader menu expected array error

---

SQF/dayz_code/compile/player_gearSync.sqf

getPosATL doesn't work for all scenarios, it's better to just use player and let the game work out if you're above water or not etc...

Fix rare occasion of gear not updating

---

SQF/dayz_code/Configs/CfgWeapons/Weapon/Rifle/FN_FAL_ANPVS4_DZE.hpp

This line fixes the "Undefined base class" error for the FN_FAL_ANPVS4_DZE you get when trying to compile dayz_code.

Fix for "Undefined base class" with FN FAL

---

SQF/dayz_code/Configs/CfgVehicles/AIR/AN2.hpp
SQF/dayz_code/Configs/CfgVehicles/AIR/Mi17.hpp
SQF/dayz_code/Configs/CfgVehicles/AIR/UH1.hpp

hiddenSelections = {}; removes the option to use custom textures on some aircrafts. Removing these lines allows to use setObjectTexture.

Remove hiddenSelections restrictions

---

Server Files/Config-Examples/instance_11_Chernarus/config.cfg
Server Files/Config-Examples/instance_12_duala/config.cfg
Server Files/Config-Examples/instance_13_tavi/config.cfg
Server Files/Config-Examples/instance_15_namalsk/config.cfg
Server Files/Config-Examples/instance_16_panthera/config.cfg
Server Files/Config-Examples/instance_18_sahrani/config.cfg
Server Files/Config-Examples/instance_19_poda/config.cfg
Server Files/Config-Examples/instance_1_takistan/config.cfg
Server Files/Config-Examples/instance_20_fapovo/config.cfg
Server Files/Config-Examples/instance_21_caribou/config.cfg
Server Files/Config-Examples/instance_22_SMDsahrani/config.cfg
Server Files/Config-Examples/instance_24_Napf/config.cfg
Server Files/Config-Examples/instance_25_sauerland/config.cfg
Server Files/Config-Examples/instance_2_utes/config.cfg
Server Files/Config-Examples/instance_3_shapur_baf/config.cfg
Server Files/Config-Examples/instance_4_zargabad/config.cfg
Server Files/Config-Examples/instance_6_Dingor/config.cfg
Server Files/Config-Examples/instance_7_Lingor/config.cfg
Server Files/Config-Examples/instance_8_ProvingGrounds_PMC/config.cfg

requiredSecureId is deprecated and pretty much useless since the OA STEAM switch.
[10:10:19 | Edited 10:10:49] David Foltyn: secureID was deprecated and replaced with STEAMid, so imho that setting is now void

Remove useless setting

---

SQF/dayz_code/Configs/cfgVehicles.hpp

In 1.0.5.1 you get an ItemSandbag when removing a round sandbag

Correct output for deconstruction round bagfence

---

SQF/dayz_code/Configs/CfgVehicles/LAND/Lada.hpp
SQF/dayz_code/Configs/CfgVehicles/LAND/Offroad_DSHKM.hpp
SQF/dayz_code/Configs/CfgVehicles/LAND/Pickup_PK.hpp
SQF/dayz_code/Configs/CfgVehicles/LAND/SUV.hpp
SQF/dayz_code/Configs/CfgVehicles/LAND/Skoda.hpp
SQF/dayz_code/Configs/CfgVehicles/LAND/UAZ.hpp
SQF/dayz_code/Configs/CfgVehicles/LAND/VWGolf.hpp
SQF/dayz_code/Configs/CfgVehicles/LAND/Volha.hpp
SQF/dayz_code/Configs/CfgVehicles/LAND/datsun.hpp
SQF/dayz_code/Configs/CfgVehicles/LAND/hilux.hpp
SQF/dayz_epoch_b/CfgServerTrader/Category/FriendlyAssaultRifle.hpp
SQF/dayz_epoch_b/CfgServerTrader/Category/NeutralAssaultRifle.hpp

Corrected UAZ pack upgrade to be consistent with other vehicle upgrades. Balanced armor upgrades in reference to other vehicles like the Vodnick and Armored SUV, made them consistent, and slightly improved them overall to make upgrades a little more worthwhile.
After reviewing all vehicles and upgrades I think a flat armor upgrade of +35 and a consistent damage resistance of 0.02099 across all upgrades would be fairly balanced resulting in:
Vodnick 85 armor, damageResistance = 0.032 (no change)
Armored SUV 80 armor, damageResistance = 0.03099 (no change)
UAZ Upgrade 40+35 = 75 armor, damageResistance = 0.02099 (-25 armor)
SUV Upgrade 25+35 = 60 armor, damageResistance = 0.02099 (+10 armor + .014)
Car Upgrade 20+35 = 55 armor, damageResistance = 0.02099 (+5 armor + varies - see below) …

Fix UAZ Cargo Upgrade & Balance Armor Upgrades

---

SQF/dayz_code/system/player_spawn_2.sqf

dayz_Magazines isn't always set before syncing the character, and especially considering this is just on a loop makes it very unreliable. If you input an empty array to the server_playerSync then it will wipe your backpack and weapons aswell. Noticed this bug when players were complaining about it since I switched completely over to extDB. I've taken a look at the HiveExt.dll source and I'm pretty sure I found a check in there to see if the array is empty, which is still a hacky fix for this. I honestly wonder what the devs of DayZ were doing when they made this mod, the coding is just horrendous. I feel like making my own version of it from scratch sometimes. Rant over... sorry lol. Back on topic, using magazines player won't record the clip count in a magazine, but the only time that …

[FIX] Inventory wiping

---

SQF/dayz_code/compile/player_antiWall.sqf

Players can get around this by getting another player to lock the vehicle as they're getting out. The action command only works if the vehicle is unlocked, using the moveInX commands it moves them instantly back in with no animation (better imo) and works if the vehicle is locked.

Fix for fix bypass

---

SQF/dayz_code/Configs/CfgMagazines/DZE/Food.hpp
SQF/dayz_code/Configs/CfgMagazines/DZE/Gems.hpp
SQF/dayz_code/Configs/CfgMagazines/DZE/Items.hpp
SQF/dayz_code/Configs/CfgMagazines/DZE/Ores.hpp
SQF/dayz_code/stringtable.xml

Moved few more hardcoded strings to stringtable, changed few russian localization strings to better. Also, can "Mixed Gas Full" be renamed to "Full Mixed Gas Can"? Current name sounds a bit weird.
Also, stringtable seems to be holding corrupted '(apostrophes). For example this line: https://github.com/EpochModTeam/DayZ-Epoch/blob/master/SQF/dayz_code/stringtable.xml#L185 Is it normal or should be fixed?

More localization support

---

SQF/dayz_code/Configs/CfgMagazines/DZE/Currency/Briefcase.hpp
SQF/dayz_code/Configs/CfgMagazines/DZE/ItemWaterbottle.hpp
SQF/dayz_code/Configs/CfgMagazines/DZE/Misc.hpp
SQF/dayz_code/stringtable.xml

- Misc.hpp fully localized, also fixed formatting to be more clear (no function changes)
- Briefcase.hpp localized
- Changed a couple of "Wood" names to "Wooden" (Wooden is more correct since it's adjective). Epoch wiki might needed to be updated as well.
Changed names:
Wood Ramp -> Wooden Ramp
Wood Crate -> Wooden Crate
Wood Bench -> Wooden Bench
Also, I plan to make another PR to vanilla DayZ. Found more hardcoded strings, probably today or tomorrow.

More work on localization support, cleanup Misc.hpp

---

SQF/dayz_code/Configs/CfgMagazines/DZE/Currency/CopperBar.hpp

The rightclick text to craft  1x 10oz copper bar was not visible

Fixed CopperBar Rightclick Text

---

SQF/dayz_code/Configs/RscDisplay/advancedTrading.hpp
SQF/dayz_code/actions/AdvancedTrading/functions/z_at_buyItems.sqf
SQF/dayz_code/actions/AdvancedTrading/functions/z_at_calcDefaultCurrencyNoImg.sqf
SQF/dayz_code/actions/AdvancedTrading/functions/z_at_displayItemInfo.sqf
SQF/dayz_code/actions/AdvancedTrading/functions/z_at_displayVehicleInfo.sqf
SQF/dayz_code/actions/AdvancedTrading/functions/z_at_displayWeaponInfo.sqf
SQF/dayz_code/actions/AdvancedTrading/functions/z_at_logTrade.sqf
SQF/dayz_code/actions/AdvancedTrading/functions/z_at_sellItems.sqf
SQF/dayz_code/actions/AdvancedTrading/init.sqf
SQF/dayz_code/stringtable.xml
SQF/dayz_server/compile/server_tradeObject.sqf

This adds combine currency option to the Advanced trading screen since @Airwaves man noticed it didn't have a way of doing it.
Updated stringtables with correct "paid" spelling and differing text for buying/selling.
This also addds proper currency checking/reporting for the log system that has been introduced, it's untidy but it works, instead of getting "user bought x for 1000 currency" in a non coins server, it will convert it to the proper 1 brief 5 10oz gold etc system (uses a new function z_calcDefaultCurrencyNoImg)
This also adds a check to see if the buy list is empty (as per the selling list) and returns text to the user informing them.
Re-arranged buy and sell so buy is on top of sell, it's a bit easier to read then.
This changes the server_tradeobject to check if it's being …

Advanced trading fixes/modifications

---

SQF/dayz_code/Configs/CfgExtra/snappoints.hpp
SQF/dayz_code/Configs/RscDisplay/doorManagement/doorAccess.hpp
SQF/dayz_code/compile/fn_selfActions.sqf

Changes to snappoints.hpp fixes issues with metal floors snapping to a cinder wall. Cinder to cinder will create small gaps and then metal floors won't properly line up unless you start with a metal floor then snap cinders. By making both the same snap size, this fixes this issue.
Changes to doorAccess.hpp makes it possible to unlock doors and downgrade them again. It was setting dze_lock_door to the players UID instead of the door code as it should so the conditions would not be met in fn_selfActions to give you additional access.
Changes to fn_selfActions refine access to certain points more accurately (the way they should be IMO)
1) Adds a check to see if the building item can be upgraded anymore before presenting the menu, this stops you receiving the "upgrade item" action even when …

Various changes (snappoints, dooraccess and fn_selfactions)

---

SQF/dayz_code/Configs/CfgWeapons/Rifles/MR43.hpp
SQF/dayz_code/actions/player_build.sqf
SQF/dayz_code/actions/player_buildingDowngrade.sqf
SQF/dayz_code/actions/player_upgrade.sqf
SQF/dayz_code/credits.txt

This fixes the issues I was having with APFL, Basically when downgrading
a locked door the ownerPUID was not getting transferred across so it was
getting a 0 PUID set on it once downgraded so you would then lose access
if there was no plot pole.
Now it correctly gets set and instead of doing 2 PVDZE_Obj_Swaps I am
using an if and else statement.
player_upgrade was also not sending the ownerID into the worldspace
field, this seems to differ from the original APFL script. I also added
in code so that if APFL was enabled and uid is 0 we claim the item with
players UID.
This fixes a typo @ebaydayz introduced to spam the .RPT on startup also
for the shotgun and a typo in the credits.

Plot for life fixes and typo fixes

---

SQF/dayz_code/Configs/CfgExtra/snappoints.hpp
SQF/dayz_code/Configs/CfgMagazines/DZE/Misc.hpp
SQF/dayz_code/Configs/CfgMagazines/DZE/ModularBuilding.hpp
SQF/dayz_code/stringtable.xml

This correctly fixes snap points for all cinder related to metal floors, especially full cinder walls.
Anything cinder will now correctly snap to full cinder walls and vice versa
Metal floors will not have gaps so you can correctly create a 1x1 cube (as it should be)
Renamed cinder_wall_kit to half_cinder_wall_kit to be in line with full_cinder_wall_kit since I felt it was confusing. cinder_wall_kit seems like it would be full to me.
Fixed a string issue when cancelling building to make it more readable.

Snap point changes

---

SQF/dayz_code/actions/AdvancedTrading/functions/z_at_buyItems.sqf
SQF/dayz_code/actions/AdvancedTrading/functions/z_at_calcPrice.sqf
SQF/dayz_code/actions/AdvancedTrading/functions/z_at_logTrade.sqf

Optimizes the code for the buyitems item listing (What was I thinking!)
Adds item count to buy/sell list (Useful for checking against backpack/vehicle storage space constraints when buying multiple items)
Small logging fix.
Moves buying check to start of SQF to save time (As per what @ebaydayz did on the sellitems SQF)

Advanced trading tidyness

---

SQF/dayz_code/Configs/CfgVehicles/DZE/ModularBuilding.hpp
SQF/dayz_code/stringtable.xml

This makes Block doorways and block garage door ways rename to Cinder doorways and
Cinder garage door ways so they will be alphabetized properly.
It was always annoying having block doorways not near cinder stuff.

Cinder block text changes

---

SQF/dayz_code/actions/AdvancedTrading/functions/z_at_fillBuyableList.sqf

This changes Advanced trading to change the item color to green if it
matches with an item that is in your inventory, in your weapon slots (main
slot and dayz_onBack) is the same backpack that you are wearing or is a vehicle you are
local to.
This brings it in line with default trader, except we're using local
here since that's all that matters and default trader returns all vehicles (which I never saw the point in)
Thanks to @ebaydayz for the suggestion.

Advanced trading change to buyables list

---

SQF/dayz_code/actions/AdvancedTrading/functions/z_at_fillBuyableList.sqf

Further changes Advanced trading buyable list to show the item as blue
if it's compatible attachment wise and ammo wise.
This will get overwritten if the player has the item in their inventory
by staying green.
Also fixes a small bug I put into my last commit by not showing up for
boats/bikes etc.

Advanced trading buyable list changes

---

SQF/dayz_code/Configs/CfgVehicles/Car/ArmoredSUV.hpp
SQF/dayz_code/Configs/CfgVehicles/Car/CAR_HATCHBACK.hpp
SQF/dayz_code/Configs/CfgVehicles/Car/CAR_SEDAN.hpp
SQF/dayz_code/Configs/CfgVehicles/Car/Kamaz.hpp
SQF/dayz_code/Configs/CfgVehicles/Car/Lada.hpp
SQF/dayz_code/Configs/CfgVehicles/Car/Offroad_DSHKM_INS.hpp
SQF/dayz_code/Configs/CfgVehicles/Car/Pickup_PK_INS.hpp
SQF/dayz_code/Configs/CfgVehicles/Car/SUV_DZ.hpp
SQF/dayz_code/Configs/CfgVehicles/Car/Skoda.hpp
SQF/dayz_code/Configs/CfgVehicles/Car/UAZ.hpp
SQF/dayz_code/Configs/CfgVehicles/Car/VWGolf.hpp
SQF/dayz_code/Configs/CfgVehicles/Car/Volha.hpp
SQF/dayz_code/Configs/CfgVehicles/Car/datsun.hpp
SQF/dayz_code/Configs/CfgVehicles/Car/hilux.hpp
SQF/dayz_code/actions/AdvancedTrading/functions/z_at_checkArrayInConfig.sqf

These changes allow the player to sell upgraded vehicles with them not
needing to be added to the trader (as to not pollute the lists). This basically
refers to an upgraded vehicle as a child of the base vehicle so it will
get the same sell price as the base vehicle.
This still follows the original trading convention, the vehicle base
needs to be in the trader category, i.e you cant sell an armored SUV at
stary vehicle trader.

Advanced trading selling upgraded vehicles.

---

CHANGE LOG 1.0.6.txt
SQF/dayz_code/Configs/CfgServerTrader/Category/NeutralAirplanes.hpp
SQF/dayz_code/Configs/CfgVehicles/Car/BRDM2_DZ.hpp
SQF/dayz_code/Configs/CfgVehicles/Car/HMMWV.hpp
SQF/dayz_code/Configs/CfgVehicles/CfgVehicles.hpp
SQF/dayz_code/Configs/CfgVehicles/Helicopter/MI17.hpp
SQF/dayz_code/Configs/CfgVehicles/Helicopter/UH60.hpp
SQF/dayz_code/Configs/CfgVehicles/Plane/AN2_DZ.hpp
SQF/dayz_code/Configs/CfgVehicles/Plane/Cessna_DZ.hpp

Ive added a lot new vehicles to the epoch configs. Most of the vehicle are used already by many admins but the vehicles have minmal cargo space, the radar function armor a way to high. I changed all vehicles to make them playable for epoch. Im not that good in that cfgVehicle thing so im not sure there are an easier ways to get the vehicles working.
Currently I did not add them to the traders. I would be fine with that but Im not sure what you guys think? 
HMMWV and BRDM2: I did not get the non ammo version working. Can someone take that part? I balanced the BRDM2 with the specs from the Vodnic. It has more fuel now but less armor.
New vehicles:
BRDM2_HQ_TK_GUE_EP1
HMMWV_Armored
HMMWV_M2
Mi17_TK_EP1
Mi17_UN_CDF_EP1
Mi17_CDF
Mi17_medevac_CDF
Mi17_medevac_Ins
Mi17_medevac_RU …

Adding many new vehicles to configs

---

SQF/dayz_code/Configs/CfgMagazines/DZE/Bulk.hpp
SQF/dayz_code/Configs/RscDisplay/RscDisplayGear.hpp
SQF/dayz_code/stringtable.xml

Extends the displayName RSC width to the same as the description (Not
sure why this was so small, it truncated longer display names)
Added localization strings for all the supply crates so they were easier
to distinguish in the gear menu.

Supply crate localization fixes

---

SQF/dayz_code/Configs/RscDisplay/plotManagement.hpp
SQF/dayz_code/actions/plotManagement/maintain_area.sqf
SQF/dayz_code/compile/fn_selfActions.sqf
SQF/dayz_code/init/variables.sqf
SQF/dayz_code/stringtable.xml
SQF/dayz_server/system/server_monitor.sqf

This replaces the "refresh" menu option with a "force maintain" option.
Allows you to maintain the base even if it doesn't need it to either get
all your items in sync or if you are going away or similar.
Tested with:
dze_permanent plot true/false
z_singlecurrency true/false
Also fixes an undefined variable error in system_monitor that was
introduced
https://github.com/EpochModTeam/DayZ-Epoch/commit/8f58baf3f286454a9f398517dc4f1980bd4d5c8e

Plot management force maintain option

---

SQF/dayz_code/actions/repair_vehicle.sqf
SQF/dayz_code/actions/salvage_vehicle.sqf
SQF/dayz_code/compile/fn_selfActions.sqf
SQF/dayz_code/configVariables.sqf
SQF/dayz_code/stringtable.xml

This adds the ability to remove salvaging from locked vehicles which helps avoid griefing
Fixes a spelling mistake for a localization string
Makes it possible to salvage 0% damaged items again, this was disabled as per
https://github.com/EpochModTeam/DayZ-Epoch/commit/3292d84b857f307571af9233dcfffe9d59a0b5e9
I've had this running on my server for a year or so with no issues (not that it doesn't affect it, i've just never seen it)
It seems to me it's rather silly you cant salvage undamaged items off a vehicle.
Removes Bicycle checking from salvage_vehicle.sqf and moves it to fn_selfactions to tidy things up, no use having a salvage menu that hangs when you can just not show the salvage menu all together.

Toggle for salvaging from locked vehicles

---

SQF/dayz_code/Configs/CfgLoot/CfgLoot.hpp
SQF/dayz_code/Configs/CfgLoot/Groups/Zombies/Doctor.hpp
SQF/dayz_code/Configs/CfgLoot/Groups/Zombies/Pilot.hpp
SQF/dayz_code/Configs/CfgLoot/Groups/Zombies/Suit.hpp
SQF/dayz_code/Configs/CfgVehicles/Zeds/Zeds.hpp

Ive added 3 more loot tables for the zombie types z_soldier_pilot, z_suit1 and z_suit2, z_doctor. That gives admins a better way to cusomize the loot table from each zombietyp.

Adding more loot table for zombies

---

SQF/dayz_code/Configs/CfgExtra/snappoints.hpp
SQF/dayz_code/actions/AdvancedTrading/functions/z_at_fillBuyableList.sqf
SQF/dayz_code/actions/snap_build.sqf

Fixes a bug with advanced trading green "you have this item" text in
buyables list, this was showing you had the item when you didn't.
Snap building typo
Snap building snap points for large cinder walls as reported by
@SmokeyBR
https://github.com/EpochModTeam/DayZ-Epoch/issues/1766#issuecomment-248021073

Advanced trading bugfix, Snap building typo and snap point fixes

---

SQF/dayz_code/Configs/CfgLoot/Groups/Buildings/Military.hpp
SQF/dayz_code/Configs/CfgLoot/Groups/Zombies/Military.hpp
SQF/dayz_code/Configs/CfgLoot/Groups/Zombies/Pilot.hpp
SQF/dayz_code/Configs/CfgLoot/Groups/Zombies/Police.hpp
SQF/dayz_code/Configs/CfgLoot/Groups/Zombies/Suit.hpp
SQF/dayz_code/Configs/CfgLoot/Groups/Zombies/Worker.hpp
SQF/dayz_code/Configs/CfgVehicles/DZE/TentStorage.hpp
SQF/dayz_code/stringtable.xml

The updates for STR_ACTIONS_2TB and STR_ACTIONS_RFROMTB are important. That fixes a very old bug. It was no really readable in german because the words were a way to long.

Updating german stringtable, tent fix, loot table changes

---

SQF/dayz_code/Configs/CfgExtra/snappoints.hpp
SQF/dayz_code/actions/AdvancedTrading/functions/z_at_buyItems.sqf
SQF/dayz_code/actions/AdvancedTrading/functions/z_at_canAfford.sqf
SQF/dayz_code/actions/AdvancedTrading/functions/z_at_changeBuySell.sqf
SQF/dayz_code/actions/AdvancedTrading/functions/z_at_fillBuyableList.sqf
SQF/dayz_code/actions/AdvancedTrading/functions/z_at_logTrade.sqf
SQF/dayz_code/actions/AdvancedTrading/functions/z_at_payDefault.sqf
SQF/dayz_code/actions/AdvancedTrading/init.sqf
SQF/dayz_code/stringtable.xml
SQF/dayz_server/compile/server_handleSafeGear.sqf
SQF/dayz_server/compile/server_tradeObject.sqf

Fixes a few issues and a dupe with advanced trading as well as some localization of where a vehicle key is going.
Z_at_buyItems: Now adds localization for the key getting added to your toolbelt, backpack and vehicle, this stops players thinking they didn't get a key when infact it was added to their backpack/vehicle.
Z_at_canAfford.sqf: This fixes a dupe from a bad copy paste for whomever wrote this script, it was using _backpackMoney in the z_allowTakingMoneyFromVehicle part, changed to the proper variable _vehicleMoney. **This would dupe your currency before**
z_at_fillBuyableList.sqf: this fixes a bug where a vehicle would show green even when it isn't local, just basically added more checking to make sure the vehicle it's making green in the list is a) local, b) alive and that the …

Advanced trading fixes, server_handleSafeGear human readibility

---

SQF/dayz_code/stringtable.xml
Server Files/SQL/1.0.6_Updates.sql

Makes MeleeHatchet_DZE for converted databases properly get renamed
Changes Destroy to Remove since you're not completely destroying it, maybe we need a different one for modular parts that wont get returned?

SQL Update fix for MeleeHatchet_DZE -> MeleeHatchet, localization fix

---

SQF/dayz_code/Configs/CfgMagazines/Clothing/Clothing.hpp
SQF/dayz_code/stringtable.xml

@oiad for some reason it is case sensitive here. It works only like that, otherwise there will stand $str_tear_clothes as rightclick option.

Fixing string is not displayed correctly

---

SQF/dayz_code/actions/player_upgrade.sqf

Adds systemChat to receive the combination for whatever you upgrade as
well as dayz_rollingMessages.
The same as what modular_build does.

player_upgrade combination addition

---

SQF/dayz_server/compile/server_updateObject.sqf

This modifies server_updateObject to force update/save to the hive if the item being saved is in the DZE_MoneyStorageClasses array. (in my testing I was using a plot pole as a coin storage object)
Previously if you force saved the object multiple times, the coins would not get updated until the inventory changed, which if this was for a bank object it would never update.
(This applies if you are using PVDZ_veh_Save to save the object)

server_updateObject force update for single currency

---

SQF/dayz_code/actions/repair_vehicle.sqf

For tanks and other vehicles not explicitly defined in configs, _part will return with "" using gettext(), evaluating if it is nil doesn't do anything. With this change it will properly allow for repairing tracks on tanks with scrap metal.

Detection of part doesn't work

---

SQF/dayz_code/actions/player_craftItem.sqf

Adding the ability to craft with all Dayz_Ignators when dayz_matchboxCount = true; For example crafting a Firebarrel

 Craft with all Dayz_Ignators

---

SQF/dayz_code/Configs/CfgVehicles/DZE/Prop_Defs.hpp

The fire barrel output should be a fire barrel not a empty fuel barrel.

Changing Fire Barrel output

---

SQF/dayz_code/actions/doorManagement/player_enterCode.sqf
SQF/dayz_code/actions/player_destroyTent.sqf
SQF/dayz_code/compile/player_unlockDoor.sqf
SQF/dayz_code/configVariables.sqf
SQF/dayz_code/init/variables.sqf
SQF/dayz_code/stringtable.xml

This adds a variable (DZE_doorManagementHarderPenalty) to make attempts at code breaking doors harder. This will exponentially increment the time between attempts or if you set it to false will make it 5 seconds between attempts.
Unlike the original (that was useless TBH) this will actually lock out the combo lock UI until the timer is set.
Will reset completely after 120 seconds.
@ebayShopper  Further to commit:
https://github.com/EpochModTeam/DayZ-Epoch/commit/0e938ba8f36b2631b98da1bdbfd3d6d578432110

Add harder penalties for wrong combination on doors, More spelling mistakes.

---

CHANGE LOG 1.0.6.1.txt
SQF/dayz_code/Configs/CfgVehicles/DZE/Doors.hpp
SQF/dayz_code/actions/AdvancedTrading/functions/z_at_logTrade.sqf
SQF/dayz_code/compile/player_unlockDoor.sqf
SQF/dayz_code/compile/player_unlockVault.sqf
SQF/dayz_server/compile/server_handleSafeGear.sqf
SQF/dayz_server/compile/server_tradeObject.sqf

This adds logging for both safes and lockboxes for failed code attempts.
Also adds logging for locking, unlocking and failed code attempts for doors.
```"salival (playerUID) FAILED unlocking LockBox with code: Red11 (actual: Red57) @110069 [11044.4,8438.32,0.652]"
"salival (playerUID) UNLOCKED LockBox with code: Green22 @110069 [11040.6,8438.91,0.834]"
"salival (playerUID) PACKED LockBox with code: Green22 @110069 [11040.6,8438.91,0.834]"
"salival (playerUID) UNLOCKED CinderWallDoorSmallLocked_DZ with code: 559 @110069 [11015.4,8458.74,5.272]"
"salival (playerUID) LOCKED CinderWallDoorSmallLocked_DZ with code: 559 @110069 [11015.4,8458.74,5.272]"
"salival (playerUID) FAILED unlocking CinderWallDoorSmallLocked_DZ with code: EYESCAN (actual: 559) @110069 [11015.4,8458.74,5.272]"
"salival …
```

Add logging failed safe/lockbox and door lock/unlock/failed code attempts

---

CHANGE LOG 1.0.6.1.txt
SQF/dayz_code/Configs/CfgVehicles/RepairParts.hpp

The merlin has 20 windows + 2 side windows, glass 7 - 20 were showing up
as PartGeneric and breaking the repair script for some reason.
https://github.com/EpochModTeam/DayZ-Epoch/issues/1856#issue-199105821

Allow merlin_hc3 to be repaired properly

---

SQF/dayz_server/compile/server_handleSafeGear.sqf

This fix makes it so that if the player used Eye Scan it will properly
show eyescan instead of the code.

Fix handleSafeGear not showing eyescan as it should.

---

SQF/dayz_server/compile/server_handleSafeGear.sqf

Was displaying failed code as the actual code (obviously wrong)

Fix handleSafeGear not showing the failed code correctly

---

SQF/dayz_code/compile/epoch_tempKeys.sqf
SQF/dayz_code/compile/fn_selfActions.sqf

epoch_tempKeys was making a massive array every time it was called due
to them setting the array size to the _ownerKeyId instead of count
_temp_keys_names.
For example: Call this function 10k times in testkit and see it lag the
client due to making a massive array over and over again.
```
"[[["9379"],[<null>,<null>,<null>,<null>,<null>,<null>,<null>,<null>,<null>,<null>,<null>,<null>,<null>,<null>,<null>,<null>,<null>,<null>,<null>,<null>,<null>,<null>,<null>,<null>,<null>,<null>,<null>,<null>,<null>,<null>,<null>,<null>,<null>,<null>,<null>,<null>,<null>,<null>,<null>,<null>,<null>,<null>,<null>,<null>,<null>,<null>,<null>,<null>,<null>,<null>,<null>,<null>,<null>,<null>,<null>,<null>,<null>,<null>,<null>,<null>,<null>,<null>,<null>,<null>,<null>,<null>,<null>,<null>,<null>,<null>,<null>, …
```

fix epoch_tempKeys.sqf making massive arrays.

---

CHANGE LOG 1.0.6.1.txt
SQF/dayz_code/compile/player_upgradeVehicle.sqf
SQF/dayz_server/compile/server_deleteObj.sqf
SQF/dayz_server/compile/server_publishVehicle3.sqf
SQF/dayz_server/compile/server_updateObject.sqf

server_publishVehicle3 first creates the vehicle in the database then
reads it back to see if it's successful, previously it wasn't deleting
the vehicle if it failed.
Added a 1 second delay after the vehicle delete to stop duping of
vehicles also.
Fixed references to server_deleteObj that were using 2 parameters
instead of the required 3 and updated the example.

Stop server_publishVehicle3 duping a vehicle if hive fails to update

---

CHANGE LOG 1.0.6.1.txt
SQF/dayz_code/actions/modular_build.sqf
SQF/dayz_code/actions/player_build.sqf
SQF/dayz_code/actions/player_buildingDowngrade.sqf
SQF/dayz_code/actions/player_upgrade.sqf
SQF/dayz_server/compile/server_publishObject.sqf
SQF/dayz_server/compile/server_swapObject.sqf

This now makes buildables properly apply godmode instead of having to
wait till restart for:
* Being built
* Being upgraded
* Being downgraded

Extend DZE_GodModeBase to newly built items

---

CHANGE LOG 1.0.6.2.txt
SQF/dayz_code/actions/modular_build.sqf
SQF/dayz_code/compile/dze_buildChecks.sqf
SQF/dayz_code/configVariables.sqf
SQF/dayz_code/init/compiles.sqf
SQF/dayz_code/stringtable.xml

This adds DZE_limitPlots where admins can restrict a player to only
having 1 plot pole. Disabled by default.

Add DZE_limitPlots so admins can limit plot poles to 1 per UID.

---

SQF/dayz_code/actions/AdvancedTrading/functions/z_at_checkCloseVehicle.sqf
SQF/dayz_code/actions/AdvancedTrading/functions/z_at_sellItems.sqf
SQF/dayz_code/init/publicEH.sqf
SQF/dayz_code/init/variables.sqf

This stops the public variable event handler from being loaded when
you're using config based traders, it's not needed in this situation

Remove public variable event handler when using config traders.

---

SQF/dayz_code/actions/AdvancedTrading/functions/z_at_fillBuyableList.sqf

This was showing you had a vehicle in the trader menu even if it was
over the other side of the map, I think this works better only showing
it if it's within the trader zone.

Dont show you have the item if it's not nearby

---

SQF/dayz_code/actions/doorManagement/doorRemoveFriend.sqf
SQF/dayz_code/actions/plotManagement/plotRemoveFriend.sqf
SQF/dayz_code/stringtable.xml

This makes it so only the door or plot owner can remove them selves from
doors/plots or the UIDS in
DZE_PlotManagementAdmins/DZE_DoorManagementAdmins.

Forbid removing the plot/door owner from objects

---

CHANGE LOG 1.0.6.2.txt
SQF/dayz_code/Configs/CfgMagazines/Magazines/127x99.hpp
SQF/dayz_code/Configs/CfgMagazines/Magazines/Magazines.hpp
SQF/dayz_code/Configs/CfgWeapons/Weapon/Sniper/AS50.hpp

The Corepatch broke some of the AS50 magazine spawns. Im not sure why it happend sometimes and sometimes not.
This message showed up sometimes: No entry 'bin\config.bin/CfgMagazines-5Rnd_127x99_as50_CP'.
The CorePatch use that: 
https://github.com/Goliath86/CorePatch/blob/e0d06f7086fb0e3b3e6b7dc22beeca3b087967be/CorePatch_CIT_14888/config.cpp
This commit should fix that error message and the AS50 name as well.

Fix Corepatch AS50 magazine spawn

---

SQF/dayz_code/compile/epoch_tempKeys.sqf

Useful for mods that require key functionality (vkc, virtual garage etc)

extend epoch_tempKeys to return key classnames also

---

SQF/dayz_code/compile/fn_damageHandler.sqf
SQF/dayz_server/compile/server_publishVehicle3.sqf
SQF/dayz_server/init/server_functions.sqf

This changes the hit messages to only show AI instead of the AI's names.
Changes this:
```
20:08:37 "P1ayer PID#7(salival) hit by PID#1(Qadeer Hakimi) with
vil_G36VA4Eot/B_556x45_Ball <ammo left:25> from 356 meters in head_hit
for 0 damage"
```
To this:
```
20:08:37 "P1ayer PID#7(salival) hit by AI with
vil_G36VA4Eot/B_556x45_Ball <ammo left:25> from 356 meters in head_hit
for 0 damage"
```
Continuity fix for hit and kill for vehicles so they match:
Before:
```
22:44:03 "P1ayer PID#3(salival) hit by AI in Pickup (PK) DZ from 15
meters in head_hit for 0.88666 damage"
```
After:
```
22:44:03 "P1ayer PID#3(salival) hit by AI with a Pickup (PK) DZ from 15
meters in head_hit for 0.88666 damage"
```
Kill message:
```
22:44:04 "salival (76561197999617086) salival was killed
by AI with a …
```

AI hit messages and continuity

---

SQF/dayz_server/compile/server_publishVehicle3.sqf

This helps stop vehicles bouncing when being upgraded.
The Vehicle Key Changer script I rewrote uses the epoch vehicle upgrade system to claim/change the vehicle key, we noticed that it was causing the vehicles to bounce, but VKC uses all the position functions from the epoch script so it's not something that VKC has introduced.

Fix vehicles bouncing when upgrading.

---

SQF/dayz_server/eventHandlers/server_sendToClient.sqf

Actually makes this functional without editing it, this is quite useful for custom scripts.

Remove comment for engine starting/stopping

---

SQF/dayz_server/compile/server_handleSafeGear.sqf

If the player enters a wrong code the algorithm can make the entered code seem completely bogus, let's just exit out of the routine if that's the case.
Sample bad code (Just hit red key):
```11:45:54 "salival (playerUID) FAILED unlocking LockBox with code: Red0-9900 (actual: Red34) @038117 [3899.36,3580.24,1.632]"```

Dont show incomplete lockbox code

---

SQF/dayz_code/actions/AdvancedTrading/functions/z_at_checkArrayInConfig.sqf

The previous fix https://github.com/EpochModTeam/DayZ-Epoch/commit/4fa36dfd94b0bbfc63a14bb28035a692101dd1b1 was not working correctly, if you had say the a stinger launcher and a stinger ammo it would detect them both as weapons, this properly classifies them and all others as how they should be.
Moved to use epoch_tempKeys also
This forces the player to only be able to sell a vehicle from the gear menu instead of backpack and vehicle menu since most of the time you would be using add all.
From: https://epochmod.com/forum/topic/44413-prevent-selling-vehicles-from-backpack/?tab=comments#comment-297328

Fix javelin/stinger selling

---

CHANGE LOG 1.0.6.2.txt
SQF/dayz_code/actions/remove.sqf
SQF/dayz_code/configVariables.sqf

This allows typically not refunded modular buildables to be configured by the server admin.
For example:
DZE_modularConfig = [
["CinderWall_DZ", [["CinderBlocks",7],["MortarBucket",2]]],
["CinderWallDoor_DZ", [["CinderBlocks",7],["MortarBucket",2],["ItemTankTrap",3],["ItemPole",[1,3]]]]
];
This would refund 7 cinder blocks and 2 mortar for "CinderWall_DZ"
For "CinderWallDoor_DZ" you would get 7 cinder blocks, 2 mortar, 3 tank traps and a random number of poles between 1 and 3.
The refund amount can be an array where the first param is the minimum and the second is the maximum, it will refund a random amount between them.
Thanks to @BigEgg17 for the suggestion and sample code.

Allow modular buildables to refund defined parts

---

SQF/dayz_code/actions/plotManagement/plotRemoveFriend.sqf
SQF/dayz_code/compile/dze_buildChecks.sqf

Additional work for https://github.com/EpochModTeam/DayZ-Epoch/commit/73899d520fd2fe523ad9b0e28618697aa0933364#diff-0cdf3d56b40b62e92b498e7362874f34
This fixes an issue of players removing them selves from a plot so a friend can become plot owner and bypass the original DZE_limitPlots check
This fixes the checking done not picking up that a player was the owner of the plot by the userlist on the plot when it wasn't them that placed it

Fix issues with DZE_limitPlots

---

SQF/dayz_code/compile/building_spawnLoot.sqf
SQF/dayz_code/compile/building_spawnZombies.sqf
SQF/dayz_code/compile/player_spawnCheck.sqf
SQF/dayz_code/compile/zombie_generate.sqf
SQF/dayz_code/init/variables.sqf
SQF/dayz_code/system/player_spawn_2.sqf

Removed a lot of redundancy in the files. Conditions were sometimes being triple checked.
Moved zombie and loot related operations from player_spawn_2 to player_spawnCheck where they are directly used.
Added lazy eval where appropriate.
Better use of global variables used in zombie and loot checks. I'm not sure why global variable values were saved to local variables since the values are changed every time something spawns.
Removing empty Cardboard boxes is no longer necessary. DayZ mod has it's own cardboard box model that inherits from parent class "ReammoBox".
https://github.com/EpochModTeam/DayZ-Epoch/blob/392f8cb7b3fe2b466fa9cf920d2879dc8d4aebe0/SQF/dayz_code/Configs/CfgVehicles/LootContainer.hpp#L33

Updates to zombie and loot spawning

---

SQF/dayz_server/compile/server_handleSafeGear.sqf

The check will always return 'false' because packedClass is a Weapon Holder (classname: WeaponHolder_xxx) and those aren't in DZE_MoneyStorageClasses.
And there's no need for that check anyway because the _isZSC variable checks if it's a money storage.

Fix safe coins refund when packing
